### ISSUE TITLE
Arc is not rendering in android studio preview mode

### ISSUE THREAD

**Issue by vipulasri** [florent37/ArcLayout#17]
Arc is not getting rendered in android studio preview mode. 

Also, getting this error in preview mode: 

```
java.awt.image.RasterFormatException: (x + width) is outside raster
	at sun.awt.image.IntegerInterleavedRaster.createWritableChild(IntegerInterleavedRaster.java:467)
	at sun.awt.image.IntegerInterleavedRaster.createChild(IntegerInterleavedRaster.java:514)
	at sun.java2d.pipe.GeneralCompositePipe.renderPathTile(GeneralCompositePipe.java:106)
	at sun.java2d.pipe.AAShapePipe.renderTiles(AAShapePipe.java:201)
	at sun.java2d.pipe.AAShapePipe.renderPath(AAShapePipe.java:159)
	at sun.java2d.pipe.AAShapePipe.fill(AAShapePipe.java:68)
	at sun.java2d.pipe.PixelToParallelogramConverter.fill(PixelToParallelogramConverter.java:164)
	at sun.java2d.pipe.ValidatePipe.fill(ValidatePipe.java:160)
	at sun.java2d.SunGraphics2D.fill(SunGraphics2D.java:2525)
	at android.graphics.BaseCanvas_Delegate.lambda$nDrawPath$9(BaseCanvas_Delegate.java:356)
	at com.android.layoutlib.bridge.impl.GcSnapshot.drawOnGraphics(GcSnapshot.java:720)
	at com.android.layoutlib.bridge.impl.GcSnapshot.drawInLayer(GcSnapshot.java:633)
	at com.android.layoutlib.bridge.impl.GcSnapshot.draw(GcSnapshot.java:601)
	at android.graphics.BaseCanvas_Delegate.draw(BaseCanvas_Delegate.java:555)
	at android.graphics.BaseCanvas_Delegate.nDrawPath(BaseCanvas_Delegate.java:324)
	at android.graphics.BaseCanvas.nDrawPath(BaseCanvas.java)
	at android.graphics.BaseCanvas.drawPath(BaseCanvas.java:298)
	at android.graphics.Canvas.drawPath(Canvas.java:1645)
	at com.github.florent37.arclayout.ArcLayout.dispatchDraw(ArcLayout.java:169)
	at android.view.View.draw(View.java:19024)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4256)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)
	at android.view.View.draw(View.java:19024)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4256)
	at android.support.design.widget.CollapsingToolbarLayout.drawChild(CollapsingToolbarLayout.java:324)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)
	at android.view.View.draw(View.java:19159)
	at android.support.design.widget.CollapsingToolbarLayout.draw(CollapsingToolbarLayout.java:286)
	at android.view.View.draw(View.java:19026)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4256)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)
	at android.view.View.draw(View.java:19159)
	at android.view.View.draw(View.java:19026)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4256)
	at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1254)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)
	at android.view.View.draw(View.java:19159)
	at android.view.View.draw(View.java:19026)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4256)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)
	at android.view.View.draw(View.java:19024)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4256)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)
	at android.view.View.draw(View.java:19024)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4256)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4256)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4042)
	at android.view.View.draw(View.java:19159)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:403)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:550)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:424)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:108)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:154)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:136)
	at com.android.tools.idea.rendering.RenderTask.lambda$renderInner$5(RenderTask.java:760)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by alimovshohrukh** [comment]
maybe late but, here is the solution https://stackoverflow.com/a/47632273/5792379

**Comment by florent37** [comment]
please try with https://github.com/florent37/ShapeOfView ?
